### ISSUE TITLE
Error while updating consumers

### ISSUE THREAD

**Issue by JnMik** [mybuilder/kongfig#33]
TypeError: apis.map is not a function
 TypeError: apis.map is not a function
    at _callee3$ (/usr/local/lib/node_modules/kongfig/lib/kongState.js:35:49)
    at tryCatch (/usr/local/lib/node_modules/kongfig/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/usr/local/lib/node_modules/kongfig/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/usr/local/lib/node_modules/kongfig/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at step (/usr/local/lib/node_modules/kongfig/lib/kongState.js:15:191)
    at /usr/local/lib/node_modules/kongfig/lib/kongState.js:15:368
    at run (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:14:5)
    at nextTickCallbackWith0Args (node.js:433:9)

I do not have this error in the insert process, but if I run the script again I have this error during the update.

I'm not sure why this is happening. 
Just sharing what I found  :)

Details:
I have 7 APIs and 18 consumers in the yml / inserted in kong.
Kong : 0.8.1
Kongfig: Latest
Casssandra: 2.2.6

**Comment by CyExy** [comment]
Does it happen consistently or sometimes? If possible could you post a config file that causes it.

**Comment by JnMik** [comment]
Let me try to build a scenario where it happends everytime.
I'll work on this today.

**Comment by JnMik** [comment]
Seems to only happens "sometimes".

I'm having a hard time building that scenario.. trying to reproduce production configs (where it currently happens) in dev with non-confidential values, but it's not working atm.

I'll update my progress later.

**Comment by CyExy** [comment]
It may be because kongfig is a little chatty and if you have a lot of definitions to check then nginx may drop the connection at some point.

I just published `kongfig@1.2.7` that has a cache layer. It makes fewer requests to kong admin api after  the first runthrough, you should have a noticeable speed increase and this problem may improve. Saying that the cache has little effect on the first run.

**Comment by JnMik** [comment]
Ok I'll give it a try !

**Comment by JnMik** [comment]
Still having the problem on one of my node in production, with 1.2.7. 

This time it  seems it happens with consumers :

TypeError: consumers.map is not a function
 TypeError: consumers.map is not a function
    at _callee3$ (/usr/local/lib/node_modules/kongfig/lib/kongState.js:70:54)
    at tryCatch (/usr/local/lib/node_modules/kongfig/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/kongfig/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/kongfig/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at step (/usr/local/lib/node_modules/kongfig/lib/kongState.js:15:191)
    at /usr/local/lib/node_modules/kongfig/lib/kongState.js:15:368
    at run (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)


Still not able to reproduce in dev.
I'll try again when I'll have a bit more time
